Unify all find functions using xpath (#59)
* fix dump_xml on python3

dump_xml returns bytes, so we need to add 'b' to file mode

Traceback (most recent call last):
  File "tests/tests.py", line 230, in test_dump_xml
    self.kp.dump_xml('db_dump')
  File "/home/evan/resources/pykeepass/pykeepass/pykeepass.py", line 81, in dump_xml
    f.write(self.kdb.pretty_print())
TypeError: write() argument must be str, not bytes

* merge all find_x_by_y functions

* integrate find_x_by_path functions

* AND results instead of OR, add test