fix dump_xml on python3 (#58)
dump_xml returns bytes, so we need to add 'b' to file mode

Traceback (most recent call last):
  File "tests/tests.py", line 230, in test_dump_xml
    self.kp.dump_xml('db_dump')
  File "/home/evan/resources/pykeepass/pykeepass/pykeepass.py", line 81, in dump_xml
    f.write(self.kdb.pretty_print())
TypeError: write() argument must be str, not bytes